library(RCurl)
library(jsonlite)
library(httr)
library(tidyverse)
library(magrittr)
library(rvest)
library(assertthat)

#' Show data types
#'
#' This function shows a table of data types the API can query
#' @keywords data, types, api
#' @examples show_data_types()
show_data_types <- function(){
  url <- "http://docs.immport.org/API/DataQueryAPI/dataqueryapi/"
  tables <- read_html(url) %>% html_nodes("table")
  df <- tables[[2]] %>% html_table() %>% as.tibble()
  return(df)
}

#' Show query filters
#'
#' This function shows a table of filters available for API
#' @keywords filter, query, api
#' @examples show_filters()
show_filters <- function(){
  url <- "http://docs.immport.org/API/DataQueryAPI/dataqueryapi/"
  tables <- read_html(url) %>% html_nodes("table")
  df <- tables[[3]] %>% html_table() %>% as.tibble()
  return(df)
}

#' Generate token function
#'
#' This function allows the user to specify their ImmPort Username and Password to generate an API token.
#' @param Username Your ImmPort username
#' @param Password Your ImmPort password
#' @keywords token
#' @examples gen_token(Username = your_user_name, Password = your_password)
gen_token <- function(Username, Password){
  tryCatch(
  t <- fromJSON(postForm("https://auth.immport.org/auth/token",
                         username = Username,
                         password = Password)),
  error=function(e) print("There was a problem generating your token, are you sure you used the right username and password?"))
  return(t$token)
}

#' Process contents of data query respone into data frame
#'
#' This function processes httr response from API into a data frame
#' @param data_query_response the http response output from the function data_query()
#' @keywords data frame
#' @examples proc_response(data_query_response)
proc_response <- function(data_query_response){
  tryCatch(
  if (grepl(data_query_response$headers$`content-type`, pattern = "json")){
    tmp <- fromJSON(content(data_query_response, "text"))
    return(tmp)
  }else{
    tmp <- content(data_query_response, "text") %>% read_delim(., "\t")
    return(tmp)
  },
  error = function(e) print("There was an error parsing the data.  The API call generating the response may have failed.")
  )
}

#' Perform query using Data Query API
#'
#' This function allows the user to use token from gen_token function  to query the ImmPort API
#' @param data_type string representing the data type of interest to query from API
#' @param token str representing the token generated by the gen_token function
#' @param filter list where each name is one ore more of filters to API and filter variables; those filters with multiple variables expressed as a vector or list
#' @keywords query
#' @examples data_query(token, data_type = "elisa", filter = list(studyAccession = c("SDY2", "SDY4"), maxSubjectAgeGte=90))
data_query <- function(token, data_type = "elisa", filter = NULL){
  assert_that(length(data_type) == 1, msg = "Only one data type at a time can be submitted to the api.")
  assert_that(data_type %in% show_data_types()$Endpoint, msg = "Data type is not available or is misspelled.  See show_data_types() function for information on available data types in the Endpoint column.")
  assert_that(all(names(filter) %in% show_filters()$`Filter Field`), msg = "One of the filters is not available or is misspelled. See show_filters() function for a list of available filters in the Filter Field column.")
  if("clinical" %in% names(filter)){assert_that(length(filter[["clinical"]]) == 1, msg = "clinical filter must have one value of Y or N")}
  if("clinical" %in% names(filter)){assert_that(filter[["clinical"]] %in% c('Y', 'N'), msg = "clinical filter must have value of Y or N")}
  if("maxSubjectAge" %in% names(filter)){assert_that(length(filter[["maxSubjectAge"]]) == 1, msg = "maxSubjectAge filter must have one exact numeric value")}
  if("maxSubjectAgeGte" %in% names(filter)){assert_that(length(filter[["maxSubjectAgeGte"]]) == 1, msg = "maxSubjectAgeGte filter must have one exact numeric value")}
  if("maxSubjectAgeLte" %in% names(filter)){assert_that(length(filter[["maxSubjectAgeLte"]]) == 1, msg = "maxSubjectAgeLte filter must have one exact numeric value")}
  if("maxSubjectAgeGt" %in% names(filter)){assert_that(length(filter[["maxSubjectAgeGt"]]) == 1, msg = "maxSubjectAgeGt filter must have one exact numeric value")}
  if("maxSubjectAgeLt" %in% names(filter)){assert_that(length(filter[["maxSubjectAgeLt"]]) == 1, msg = "maxSubjectAgeLt filter must have one exact numeric value")}
  if("minSubjectAge" %in% names(filter)){assert_that(length(filter[["minSubjectAge"]]) == 1, msg = "minSubjectAge filter must have one exact numeric value")}
  if("minSubjectAgeGte" %in% names(filter)){assert_that(length(filter[["minSubjectAgeGte"]]) == 1, msg = "minSubjectAgeGte filter must have one exact numeric value")}
  if("minSubjectAgeLte" %in% names(filter)){assert_that(length(filter[["minSubjectAgeLte"]]) == 1, msg = "minSubjectAgeLte filter must have one exact numeric value")}
  if("minSubjectAgeGt" %in% names(filter)){assert_that(length(filter[["minSubjectAgeGt"]]) == 1, msg = "minSubjectAgeGt filter must have one exact numeric value")}
  if("minSubjectAgeLt" %in% names(filter)){assert_that(length(filter[["minSubjectAgeLt"]]) == 1, msg = "minSubjectAgeLt filter must have one exact numeric value")}
  if("studyTimeCollected" %in% names(filter)){assert_that(length(filter[["studyTimeCollected"]]) == 1, msg = "studyTimeCollected filter must have one exact numeric value")}
  if("studyTimeCollectedGte" %in% names(filter)){assert_that(length(filter[["studyTimeCollectedGte"]]) == 1, msg = "studyTimeCollectedGte filter must have one exact numeric value")}
  if("studyTimeCollectedLte" %in% names(filter)){assert_that(length(filter[["studyTimeCollectedLte"]]) == 1, msg = "studyTimeCollectedLte filter must have one exact numeric value")}
  if("studyTimeCollectedGt" %in% names(filter)){assert_that(length(filter[["studyTimeCollectedGt"]]) == 1, msg = "studyTimeCollectedGt filter must have one exact numeric value")}
  if("studyTimeCollectedLt" %in% names(filter)){assert_that(length(filter[["studyTimeCollectedLt"]]) == 1, msg = "studyTimeCollectedLt filter must have one exact numeric value")}
  if("format" %in% names(filter)){assert_that(length(filter[["format"]]) == 1, msg = "format filter must have one value of json or tsv")}

  tmp <- GET(paste(paste("https://api.immport.org/data/query/result/",data_type, sep = ""),
                   URLencode(paste(sapply(1:length(filter),
                                          FUN = function(i) paste(names(filter)[i],
                                                                  paste(filter[[i]],
                                                                        collapse = ","),
                                                                  sep = "=")),
                                   collapse = "&")),
                   sep = "?"),
             accept_json(),
             add_headers('Authorization' = paste('bearer', token, sep = " ")))
  return(tmp)
}
